stages:
    - testes
    - build
    - deploy 

executar_teste:
  stage: testes
  before_script:
    - echo "Preparando testes..."

  script:
    - echo "Executando testes..."

  after_script:
    - echo "Apagando arquivos temporários..."

executar_teste2:
  stage: testes
  only:
    - main
  script:    
    - echo "Executando testes 2..."

criar_imagens:
  only:
    - main
  stage: build

  script:
    - echo "Criando as imagens..."
    - pwd
    - ls
    - cat /etc/os-release
    - mkdir pipeline
    - ls

push_imagens:
  only:
    - main
  needs:
    - criar_imagens 
  stage: build
  script:
    - echo "Realizando upload das imagens..."

kubernetes:
  only:
    - main
  stage: deploy
  script:
    - echo "Executando deploy..."
